let grants = JSON.parse(localStorage.getItem('ledgerly-grants') || '[]');
let expenses = JSON.parse(localStorage.getItem('ledgerly-expenses-v3') || '[]');
let earnings = JSON.parse(localStorage.getItem('physicode-earnings') || '[]');
let activeGrant = 'all';
let editingExpenseId = null, editingEarningId = null, editingGrantIndex = null, currentView = 'dashboard';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const money = n => new Intl.NumberFormat('en-SG',{style:'currency',currency:'SGD'}).format(n);
const spentFor = name => expenses.filter(e=>e.grant===name).reduce((sum,e)=>sum+e.amount,0);
const initials = n => n==='Company account'?'CO':n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
const iconFor = c => c.includes('Software')?'⌘':c.includes('Prototype')?'◇':c.includes('Travel')?'↗':'◌';
const palette = [['#235d4a','#e7f1ed'],['#6675c4','#eceefa'],['#c08a35','#fbf1df'],['#a75e6b','#f8e9ed'],['#43819b','#e7f2f6']];
const teamMembers = ['Atharva','Raghav','Dan','Ishaan','Kevin'].sort(() => Math.random() - 0.5);
$('#payerName').innerHTML = '<option value="">Select teammate</option>' + teamMembers.map(name => `<option>${name}</option>`).join('');
$('#teamDirectory').innerHTML = teamMembers.map(name => `<article><i>${name.slice(0,2).toUpperCase()}</i><div><strong>${name}</strong><small>Team member</small></div></article>`).join('');

function rowHTML(e,full=false){const reimbursement=e.payerType==='personal'?(e.reimbursementStatus==='reimbursed'?' · reimbursed':' · reimbursement due'):'';const doc=e.document?`<span class="doc">▤ ${e.document}</span>`:'<span class="status needs-receipt">Missing</span>';return `<tr><td><div class="expense-name"><i>${iconFor(e.category)}</i><span><strong>${e.description}</strong><small>${e.category} · ${e.quantity||1} × ${money(e.unitPrice||e.amount)}</small></span></div></td><td><span class="grant-pill">${e.grant}</span></td><td><div class="payer"><span class="mini-avatar">${initials(e.payer)}</span><span>${e.payer}<small>${reimbursement}</small></span></div></td><td>${e.date}</td><td class="amount">${money(e.amount)}</td><td><span class="status ${e.status.toLowerCase().replaceAll(' ','-')}">${e.status}</span></td><td><div class="record-cell">${full?doc:''}<div class="row-actions"><button onclick="editExpense(${e.id})">Edit</button><button class="delete" onclick="deleteExpense(${e.id})">Delete</button></div></div></td></tr>`}
function emptyRow(message='No expenses yet'){return `<tr class="empty-row"><td colspan="7"><div><span>▤</span><strong>${message}</strong><small>Add an expense and choose company revenue or an active grant.</small><button onclick="openExpenseModal()">＋ Add expense</button></div></td></tr>`}
function refreshSelects(){const options=grants.filter(g=>g.status==='Active').map(g=>`<option>${g.name}</option>`).join('');$('#expenseGrant').innerHTML=`<option>Company revenue</option>${options}`;$('#grantFilter').innerHTML=`<option value="all">All funding sources</option><option>Company revenue</option>${options}`}
function renderGrantCards(){
  if(!grants.length){$('#grantCards').innerHTML='<article class="grant-empty"><span>◈</span><div><h3>No grants added yet</h3><p>Use “Add grant” above to create your first restricted funding budget.</p></div></article>';return}
  $('#grantCards').innerHTML=grants.map(g=>{const spent=spentFor(g.name),confirmed=g.status==='Active',pct=g.amount?Math.min(100,spent/g.amount*100):0;return `<button class="grant-card" data-grant="${g.name}"><div class="grant-top"><span class="grant-logo" style="background:${g.soft};color:${g.color}">${g.initials}</span><span class="grant-status ${confirmed?'active':'pending'}">${g.status}</span></div><h3>${g.name}</h3><p>${g.notes|| (confirmed?'Grant awarded':'Awaiting result')}</p><strong>${money(g.amount)}</strong><div class="grant-progress"><i style="width:${pct}%;background:${g.color}"></i></div><div class="grant-numbers"><span>${money(spent)} used</span><span>${confirmed?money(Math.max(0,g.amount-spent))+' left':'Not included yet'}</span></div></button>`}).join('');$$('.grant-card').forEach(card=>card.onclick=()=>showGrantWithFilters(card.dataset.grant));
}
function renderGrantManagement(){const target=$('#grantManagementGrid');if(!grants.length){target.innerHTML='<article class="grant-empty"><span>◈</span><div><h3>No grants yet</h3><p>Add your first grant to begin tracking a restricted budget.</p></div></article>';return}target.innerHTML=grants.map((g,index)=>{const spent=spentFor(g.name),remaining=g.amount-spent,pct=g.amount?Math.min(100,spent/g.amount*100):0;return `<article class="managed-grant"><div class="grant-top"><span class="grant-logo" style="background:${g.soft};color:${g.color}">${g.initials}</span><span class="grant-status ${g.status==='Active'?'active':'pending'}">${g.status}</span></div><h3>${g.name}</h3><p>${g.notes||'No notes added'}</p><div class="managed-values"><span><small>Award</small><strong>${money(g.amount)}</strong></span><span><small>Used</small><strong>${money(spent)}</strong></span><span><small>Remaining</small><strong>${money(remaining)}</strong></span></div><div class="grant-progress"><i style="width:${pct}%;background:${g.color}"></i></div><div class="managed-actions"><button onclick="showGrantByIndex(${index})">View expenses</button><button onclick="editGrant(${index})">Edit</button><button class="delete" onclick="deleteGrant(${index})">Delete</button></div></article>`}).join('')}
function renderAllocation(){const activeGrants=grants.filter(g=>g.status==='Active'),grantFunds=activeGrants.reduce((a,g)=>a+g.amount,0),earnedFunds=earnings.reduce((a,e)=>a+e.amount,0),totalFunds=grantFunds+earnedFunds,eligible=new Set([...activeGrants.map(g=>g.name),'Company revenue']),spent=expenses.filter(e=>eligible.has(e.grant)).reduce((a,e)=>a+e.amount,0),available=totalFunds-spent,availablePercent=totalFunds?Math.max(0,Math.min(100,available/totalFunds*100)):0,ring=`#6c3974 0 ${availablePercent}%,#e8dfea ${availablePercent}% 100%`;$('#fundingAllocation').innerHTML=totalFunds?`<div class="balance-circle-layout"><div class="balance-circle" style="background:conic-gradient(${ring})" role="img" aria-label="${money(Math.max(0,available))} available from ${money(totalFunds)} received"><div><strong class="${available<0?'negative':''}">${money(available)}</strong><span>${available<0?'Overspent':'Available'}</span></div></div><div class="balance-details"><div class="balance-total"><span>Total funds received</span><strong>${money(totalFunds)}</strong></div><div class="balance-breakdown"><span><small>Grants</small><strong>${money(grantFunds)}</strong></span><span><small>Earnings</small><strong>+ ${money(earnedFunds)}</strong></span><span><small>Expenses</small><strong>− ${money(spent)}</strong></span></div></div></div>`:'<div class="balance-empty"><span>◎</span><div><strong>No company funds yet</strong><p>Add an active grant or record earnings to start the live balance.</p></div></div>'}
function render(){
  refreshSelects();renderGrantCards();renderGrantManagement();renderAllocation();renderEarnings();$('#expenseRows').innerHTML=expenses.length?expenses.slice(0,5).map(e=>rowHTML(e)).join(''):emptyRow();renderAll();
  const confirmed=grants.filter(g=>g.status==='Active'),grantTotal=confirmed.reduce((a,g)=>a+g.amount,0),eligible=new Set([...confirmed.map(g=>g.name),'Company revenue']),revenueTotal=earnings.reduce((a,e)=>a+e.amount,0),totalSpent=expenses.filter(e=>eligible.has(e.grant)).reduce((a,e)=>a+e.amount,0);
  const reimbursements=expenses.filter(e=>e.payerType==='personal'&&e.reimbursementStatus!=='reimbursed').length,missingDocs=expenses.filter(e=>!e.document).length,pendingApprovals=expenses.filter(e=>e.status==='Pending').length;
  $('#grantCount').textContent=grants.length;$('#grantStat').textContent=`${grants.length} grant${grants.length===1?'':'s'}`;$('#earningCount').textContent=earnings.length;$('#earningTrend').textContent=`${earnings.length} entr${earnings.length===1?'y':'ies'}`;$('#expenseCount').textContent=expenses.length;$('#reimburseCount').textContent=reimbursements;$('#reviewReimburseCount').textContent=reimbursements;$('#reviewDocumentCount').textContent=missingDocs;$('#reviewPendingCount').textContent=pendingApprovals;$('#totalAwarded').textContent=money(grantTotal+revenueTotal);$('#totalSpent').textContent=money(totalSpent);$('#spentTrend').textContent=`${grantTotal+revenueTotal?Math.round(totalSpent/(grantTotal+revenueTotal)*100):0}% used`;$('#fundsRemaining').textContent=money(grantTotal+revenueTotal-totalSpent);$('#totalEarnings').textContent=money(revenueTotal);
}
function renderEarnings(){const total=earnings.reduce((a,e)=>a+e.amount,0),spent=expenses.filter(e=>e.grant==='Company revenue').reduce((a,e)=>a+e.amount,0);$('#earningTotal').textContent=money(total);$('#revenueSpent').textContent=money(spent);$('#revenueAvailable').textContent=money(total-spent);$('#earningRows').innerHTML=earnings.length?earnings.map(e=>`<tr><td><div class="expense-name"><i>↙</i><span><strong>${e.description}</strong><small>${e.quantity||1} × ${money(e.unitPrice||e.amount)}${e.document?' · document attached':''}</small></span></div></td><td><span class="grant-pill">${e.type}</span></td><td>${e.customer}</td><td>${e.date}</td><td class="amount positive">+${money(e.amount)}</td><td>${e.reference||'—'}</td><td><div class="row-actions"><button onclick="editEarning(${e.id})">Edit</button><button class="delete" onclick="deleteEarning(${e.id})">Delete</button></div></td></tr>`).join(''):'<tr class="empty-row"><td colspan="7"><div><span>↙</span><strong>No earnings recorded yet</strong><small>Record product sales, school purchases or other income.</small><button onclick="openEarningModal()">＋ Add earning</button></div></td></tr>'}
function configureExpenseFilters(view){const filter=$('#statusFilter');filter.classList.remove('hidden');filter.dataset.mode='approval';if(view==='documents'){filter.dataset.mode='document';filter.innerHTML='<option value="all">All documents</option><option value="attached">Receipt attached</option><option value="missing">Missing receipt</option>'}else if(view==='team'){filter.dataset.mode='teammate';filter.innerHTML='<option value="all">All team members</option>'+team.map(name=>`<option value="${name}">${name}</option>`).join('')}else if(view==='reimbursements'){filter.classList.add('hidden');filter.innerHTML='<option value="all">Outstanding reimbursements</option>'}else{filter.innerHTML='<option value="all">All approval statuses</option><option value="Approved">Approved</option><option value="Pending">Pending</option>'}filter.value='all'}
function filteredExpenses(){const q=($('#tableSearch')?.value||'').toLowerCase(),filter=$('#statusFilter'),value=filter?.value||'all',mode=filter?.dataset.mode||'approval',grant=activeGrant!=='all'?activeGrant:($('#grantFilter')?.value||'all');return expenses.filter(e=>{if(currentView==='reimbursements'&&!(e.payerType==='personal'&&e.reimbursementStatus!=='reimbursed'))return false;if(currentView==='team'&&e.payerType!=='personal')return false;const matchesFilter=value==='all'||(mode==='approval'&&e.status===value)||(mode==='document'&&value==='attached'&&!!e.document)||(mode==='document'&&value==='missing'&&!e.document)||(mode==='teammate'&&e.payer===value);return matchesFilter&&(grant==='all'||e.grant===grant)&&Object.values(e).join(' ').toLowerCase().includes(q)})}
function renderAll(){const list=filteredExpenses();$('#allExpenseRows').innerHTML=list.length?list.map(e=>rowHTML(e,true)).join(''):emptyRow(activeGrant==='all'?'No expenses yet':`No expenses charged to ${activeGrant}`)}

const expenseModal=$('#modalBackdrop'),grantModal=$('#grantModal'),earningModal=$('#earningModal');
function openExpenseModal(){expenseModal.classList.remove('hidden');document.body.style.overflow='hidden';if(activeGrant!=='all')$('#expenseGrant').value=activeGrant;setTimeout(()=>document.querySelector('[name=description]').focus(),50)}
function closeExpenseModal(){expenseModal.classList.add('hidden');document.body.style.overflow='';$('#expenseForm').reset();editingExpenseId=null;$('#modalTitle').textContent='Add an expense';$('#expenseTotalPreview').textContent=money(0);$('#personalFields').classList.add('hidden');$('#dueDateField').classList.remove('hidden');$('#uploadZone').classList.remove('has-file');$('#uploadText').textContent='Drop a PDF or image here, or click to browse · Max 10 MB'}
function openGrantModal(){grantModal.classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>document.querySelector('#grantForm [name=name]').focus(),50)}
function closeGrantModal(){grantModal.classList.add('hidden');document.body.style.overflow='';$('#grantForm').reset();editingGrantIndex=null;$('#grantModal h2').textContent='Add a grant';$('#grantForm .primary-button').textContent='Add grant'}
function openEarningModal(){earningModal.classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>document.querySelector('#earningForm [name=description]').focus(),50)}
function closeEarningModal(){earningModal.classList.add('hidden');document.body.style.overflow='';$('#earningForm').reset();editingEarningId=null;$('#earningModal h2').textContent='Add an earning';$('#earningTotalPreview').textContent=money(0);$('#earningUploadText').textContent='Upload a PDF or image · Max 10 MB'}
function editExpense(id){const item=expenses.find(e=>e.id===id);if(!item)return;editingExpenseId=id;openExpenseModal();$('#modalTitle').textContent='Edit expense';const form=$('#expenseForm');form.elements.description.value=item.description;form.elements.quantity.value=item.quantity||1;form.elements.unitPrice.value=item.unitPrice||item.amount;form.elements.date.value=item.dateISO;form.elements.grant.value=item.grant;form.elements.category.value=item.category;form.elements.status.value=item.status;form.elements.payerType.value=item.payerType;form.elements.payerName.value=item.payer||'';form.elements.reimbursementStatus.value=item.reimbursementStatus||'needs';form.elements.dueDate.value=item.dueDate||'';form.elements.notes.value=item.notes||'';$('#personalFields').classList.toggle('hidden',item.payerType!=='personal');$('#dueDateField').classList.toggle('hidden',item.reimbursementStatus==='reimbursed');$('#expenseTotalPreview').textContent=money(item.amount);if(item.document)$('#uploadText').textContent=`Current: ${item.document} · choose a file to replace`}
function editEarning(id){const item=earnings.find(e=>e.id===id);if(!item)return;editingEarningId=id;openEarningModal();$('#earningModal h2').textContent='Edit earning';const form=$('#earningForm');form.elements.description.value=item.description;form.elements.quantity.value=item.quantity||1;form.elements.unitPrice.value=item.unitPrice||item.amount;form.elements.date.value=item.dateISO;form.elements.type.value=item.type;form.elements.customer.value=item.customer;form.elements.reference.value=item.reference||'';$('#earningTotalPreview').textContent=money(item.amount);if(item.document)$('#earningUploadText').textContent=`Current: ${item.document} · choose a file to replace`}
async function deleteExpense(id){if(!confirm('Delete this expense? This cannot be undone.'))return;expenses=expenses.filter(e=>e.id!==id);localStorage.setItem('ledgerly-expenses-v3',JSON.stringify(expenses));render();showToast('Expense deleted','All balances have been recalculated.');try{await syncToGoogle({action:'deleteExpense',id})}catch{}}
async function deleteEarning(id){if(!confirm('Delete this earning? This cannot be undone.'))return;earnings=earnings.filter(e=>e.id!==id);localStorage.setItem('physicode-earnings',JSON.stringify(earnings));render();showToast('Earning deleted','Company revenue has been recalculated.');try{await syncToGoogle({action:'deleteEarning',id})}catch{}}
window.editExpense=editExpense;window.editEarning=editEarning;window.deleteExpense=deleteExpense;window.deleteEarning=deleteEarning;
function showGrantWithFilters(name){currentView='grant';configureExpenseFilters('expenses');showGrant(name)}
function showGrantByIndex(index){if(grants[index])showGrantWithFilters(grants[index].name)}
function editGrant(index){const grant=grants[index];if(!grant)return;editingGrantIndex=index;openGrantModal();$('#grantModal h2').textContent='Edit grant';$('#grantForm .primary-button').textContent='Save changes';const form=$('#grantForm');form.elements.name.value=grant.name;form.elements.amount.value=grant.amount;form.elements.status.value=grant.status;form.elements.notes.value=grant.notes||''}
async function deleteGrant(index){const grant=grants[index];if(!grant)return;const linked=expenses.filter(e=>e.grant===grant.name).length;const warning=linked?` ${linked} linked expense${linked===1?'':'s'} will be moved to Company revenue.`:'';if(!confirm(`Delete ${grant.name}?${warning}`))return;expenses=expenses.map(e=>e.grant===grant.name?{...e,grant:'Company revenue'}:e);grants.splice(index,1);localStorage.setItem('ledgerly-grants',JSON.stringify(grants));localStorage.setItem('ledgerly-expenses-v3',JSON.stringify(expenses));render();showToast('Grant deleted','Company totals and linked records were updated.');try{await syncToGoogle({action:'deleteGrant',name:grant.name,reassign:true})}catch(err){showToast('Grant deleted locally','Google sync failed; check Integrations.')}}
window.showGrantByIndex=showGrantByIndex;window.editGrant=editGrant;window.deleteGrant=deleteGrant;window.openExpenseModal=openExpenseModal;window.openGrantModal=openGrantModal;window.openEarningModal=openEarningModal;$('#addExpenseTop').onclick=openExpenseModal;$('#genericAdd').onclick=openExpenseModal;$('#addGrant').onclick=openGrantModal;$('#addGrantPage').onclick=openGrantModal;$('#addEarning').onclick=openEarningModal;$('#closeModal').onclick=closeExpenseModal;$('#cancelModal').onclick=closeExpenseModal;$('#closeGrantModal').onclick=closeGrantModal;$('#cancelGrantModal').onclick=closeGrantModal;$('#closeEarningModal').onclick=closeEarningModal;$('#cancelEarningModal').onclick=closeEarningModal;expenseModal.onclick=e=>{if(e.target===expenseModal)closeExpenseModal()};grantModal.onclick=e=>{if(e.target===grantModal)closeGrantModal()};earningModal.onclick=e=>{if(e.target===earningModal)closeEarningModal()};
$$('[name=payerType]').forEach(r=>r.onchange=()=>{$('#personalFields').classList.toggle('hidden',r.value!=='personal'||!r.checked);document.querySelector('[name=payerName]').required=r.value==='personal'&&r.checked});
$('[name=reimbursementStatus]').onchange=e=>$('#dueDateField').classList.toggle('hidden',e.target.value==='reimbursed');
$('#documentInput').onchange=e=>{const f=e.target.files[0];if(f){$('#uploadZone').classList.add('has-file');$('#uploadText').textContent=`${f.name} · ${(f.size/1024).toFixed(0)} KB selected`}};
$('#earningDocumentInput').onchange=e=>{const f=e.target.files[0];if(f)$('#earningUploadText').textContent=`${f.name} · ${(f.size/1024).toFixed(0)} KB selected`};
function filePayload(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type,data:String(reader.result).split(',')[1]});reader.onerror=reject;reader.readAsDataURL(file)})}
async function syncToGoogle(payload){const url=localStorage.getItem('ledgerly-script-url');if(!url)return {connected:false};await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});return {connected:true}}
function showToast(title,message){$('#toast strong').textContent=title;$('#toast small').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500)}
$('#grantForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),editIndex=editingGrantIndex,name=String(f.get('name')).trim(),previous=editIndex===null?null:grants[editIndex];if(grants.some((g,i)=>i!==editIndex&&g.name.toLowerCase()===name.toLowerCase()))return showToast('Grant already exists','Use a different grant name.');const colors=previous?[previous.color,previous.soft]:palette[grants.length%palette.length],grant={name,amount:Number(f.get('amount')),status:f.get('status'),notes:f.get('notes'),color:colors[0],soft:colors[1],initials:name.split(' ').map(x=>x[0]).join('').slice(0,3).toUpperCase()};if(previous){grants[editIndex]=grant;if(previous.name!==name){expenses=expenses.map(x=>x.grant===previous.name?{...x,grant:name}:x);localStorage.setItem('ledgerly-expenses-v3',JSON.stringify(expenses))}}else grants.push(grant);localStorage.setItem('ledgerly-grants',JSON.stringify(grants));render();closeGrantModal();try{const synced=await syncToGoogle({action:previous?'updateGrant':'addGrant',grant,oldName:previous&&previous.name});showToast(previous?'Grant updated':'Grant added',synced.connected?'Also synced to Google Sheets.':'All company views are up to date.')}catch(err){showToast(previous?'Grant updated locally':'Grant saved locally','Google sync failed; check Integrations.')}};
$('#expenseForm').oninput=()=>{const quantity=Number($('#expenseForm [name=quantity]').value)||0,price=Number($('#expenseForm [name=unitPrice]').value)||0;$('#expenseTotalPreview').textContent=money(quantity*price)};
$('#expenseForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),personal=f.get('payerType')==='personal',file=$('#documentInput').files[0],quantity=Number(f.get('quantity')),unitPrice=Number(f.get('unitPrice')),editId=editingExpenseId,previous=expenses.find(x=>x.id===editId)||{},expense={...previous,id:editId||Date.now(),description:f.get('description'),quantity,unitPrice,category:f.get('category'),grant:f.get('grant'),payer:personal?f.get('payerName'):'Company account',payerType:f.get('payerType'),reimbursementStatus:personal?f.get('reimbursementStatus'):'not_applicable',dueDate:personal&&f.get('reimbursementStatus')==='needs'?f.get('dueDate'):'',date:new Date(f.get('date')+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),dateISO:f.get('date'),amount:quantity*unitPrice,status:f.get('status'),document:file?file.name:(previous.document||''),notes:f.get('notes'),syncStatus:'local'};if(editId)expenses=expenses.map(x=>x.id===editId?expense:x);else expenses.unshift(expense);localStorage.setItem('ledgerly-expenses-v3',JSON.stringify(expenses));render();closeExpenseModal();try{const synced=await syncToGoogle({action:editId?'updateExpense':'addExpense',expense,file:await filePayload(file)});expense.syncStatus=synced.connected?'synced':'local';localStorage.setItem('ledgerly-expenses-v3',JSON.stringify(expenses));showToast(editId?'Expense updated':'Expense saved',synced.connected?'Google Sheet updated successfully.':'Your balances are up to date.')}catch(err){showToast('Expense saved locally','Google sync failed; reconnect in Integrations.')}};
$('#earningForm').oninput=()=>{const quantity=Number($('#earningForm [name=quantity]').value)||0,price=Number($('#earningForm [name=unitPrice]').value)||0;$('#earningTotalPreview').textContent=money(quantity*price)};
$('#earningForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),file=$('#earningDocumentInput').files[0],quantity=Number(f.get('quantity')),unitPrice=Number(f.get('unitPrice')),editId=editingEarningId,previous=earnings.find(x=>x.id===editId)||{},keepOpen=!editId&&e.submitter?.value==='another',savedDate=f.get('date'),savedType=f.get('type'),earning={...previous,id:editId||Date.now(),description:f.get('description'),quantity,unitPrice,amount:quantity*unitPrice,dateISO:savedDate,date:new Date(savedDate+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),type:savedType,customer:f.get('customer'),reference:f.get('reference'),document:file?file.name:(previous.document||'')};if(editId)earnings=earnings.map(x=>x.id===editId?earning:x);else earnings.unshift(earning);localStorage.setItem('physicode-earnings',JSON.stringify(earnings));render();if(keepOpen){e.target.reset();e.target.elements.date.value=savedDate;e.target.elements.type.value=savedType;e.target.elements.quantity.value=1;$('#earningTotalPreview').textContent=money(0);$('#earningUploadText').textContent='Upload a PDF or image · Max 10 MB';e.target.elements.description.focus()}else closeEarningModal();try{const synced=await syncToGoogle({action:editId?'updateEarning':'addEarning',earning,file:await filePayload(file)});showToast(editId?'Earning updated':'Earning recorded',synced.connected?'Google Sheet updated successfully.':keepOpen?'Ready for the next sale.':'Company revenue funds are now updated.')}catch(err){showToast('Earning saved locally','Google sync failed; reconnect in Integrations.')}};

const views={expenses:['Expenses','Every purchase, invoice and receipt in one place.'],reimbursements:['Reimbursements','See who paid personally and what the company owes them.'],documents:['Documents','Keep receipts and invoices organized for every transaction.'],team:['Team spending','Understand spend and outstanding balances by team member.'],grants:['Grants','Create and review your company funding sources.']};
function showView(name){activeGrant='all';currentView=name;configureExpenseFilters(name);render();$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#dashboardView').classList.add('hidden');$('#genericView').classList.add('hidden');$('#integrationView').classList.add('hidden');$('#earningsView').classList.add('hidden');$('#grantsView').classList.add('hidden');$('#teamDirectory').classList.add('hidden');if(name==='dashboard')$('#dashboardView').classList.remove('hidden');else if(name==='grants')$('#grantsView').classList.remove('hidden');else if(name==='earnings')$('#earningsView').classList.remove('hidden');else if(name==='integrations'){$('#integrationView').classList.remove('hidden');updateConnectionUI()}else{$('#genericView').classList.remove('hidden');$('#grantDetailSummary').classList.add('hidden');$('#teamDirectory').classList.toggle('hidden',name!=='team');$('#genericTitle').textContent=views[name][0];$('#genericSubtitle').textContent=views[name][1];$('#grantFilter').classList.remove('hidden');$('#genericAdd').textContent='＋ Add expense';$('#genericAdd').onclick=openExpenseModal;renderAll()}if(innerWidth<760)$('.sidebar').classList.remove('open')}
function showGrant(name){const grant=grants.find(g=>g.name===name);if(!grant)return showView('grants');const spent=spentFor(name),remaining=Math.max(0,grant.amount-spent),pct=grant.amount?Math.min(100,spent/grant.amount*100):0;activeGrant=name;$('#dashboardView').classList.add('hidden');$('#integrationView').classList.add('hidden');$('#earningsView').classList.add('hidden');$('#grantsView').classList.add('hidden');$('#genericView').classList.remove('hidden');$('#grantDetailSummary').classList.remove('hidden');$('#genericTitle').textContent=name;$('#genericSubtitle').textContent=grant.status==='Active'?'Grant budget and every expense charged to it.':'Potential grant · not included in company funds until awarded.';$('#grantFilter').classList.add('hidden');$('#genericAdd').textContent='＋ Add expense';$('#genericAdd').onclick=openExpenseModal;$('#grantDetailSummary').innerHTML=`<article><span>Award amount</span><strong>${money(grant.amount)}</strong></article><article><span>Funds used</span><strong>${money(spent)}</strong></article><article><span>Remaining</span><strong>${money(remaining)}</strong></article><article class="usage"><span>Budget used</span><strong>${pct.toFixed(1)}%</strong><div><i style="width:${pct}%"></i></div></article>`;renderAll()}
function showReview(type){const config={reimbursements:['Reimbursements due','Team-paid expenses that still need repayment.',e=>e.payerType==='personal'&&e.reimbursementStatus!=='reimbursed'],documents:['Missing documents','Expenses that still need an invoice or receipt.',e=>!e.document],pending:['Pending approval','Expenses waiting for review.',e=>e.status==='Pending']}[type];showView(type==='reimbursements'?'reimbursements':'expenses');$('#genericTitle').textContent=config[0];$('#genericSubtitle').textContent=config[1];const list=expenses.filter(config[2]);$('#allExpenseRows').innerHTML=list.length?list.map(e=>rowHTML(e,true)).join(''):emptyRow(`No ${config[0].toLowerCase()}`)}
function updateConnectionUI(){const url=localStorage.getItem('ledgerly-script-url')||'';$('#scriptUrl').value=url;$('#connectionBadge').textContent=url?'Connected':'Not connected';$('#connectionBadge').classList.toggle('connected',!!url);$('#syncCardTitle').textContent=url?'Google sync connected':'Google sync not connected';$('#syncCardText').textContent=url?'New entries and documents will back up automatically.':'Connect Sheets and Drive to back up entries and documents automatically.';$('#connectNow').textContent=url?'View setup':'Connect'}
$('#connectionForm').onsubmit=e=>{e.preventDefault();const url=$('#scriptUrl').value.trim();localStorage.setItem('ledgerly-script-url',url);updateConnectionUI();showToast('Google connected','New entries will sync automatically.')};$('#disconnectButton').onclick=()=>{localStorage.removeItem('ledgerly-script-url');updateConnectionUI();showToast('Google disconnected','New entries will remain in this browser.')};
$('#reviewReimbursements').onclick=()=>showReview('reimbursements');$('#reviewDocuments').onclick=()=>showReview('documents');$('#reviewPending').onclick=()=>showReview('pending');$('#connectNow').onclick=()=>showView('integrations');
$$('.nav-item').forEach(n=>n.onclick=()=>showView(n.dataset.view));$$('[data-view-link]').forEach(n=>n.onclick=()=>showView(n.dataset.viewLink));$('#tableSearch').oninput=renderAll;$('#statusFilter').onchange=renderAll;$('#grantFilter').onchange=renderAll;$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){showView('expenses');$('#tableSearch').value=e.target.value;renderAll()}};$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeExpenseModal();closeGrantModal();closeEarningModal()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}});
function reloadSharedState(){grants=JSON.parse(localStorage.getItem('ledgerly-grants')||'[]');expenses=JSON.parse(localStorage.getItem('ledgerly-expenses-v3')||'[]');earnings=JSON.parse(localStorage.getItem('physicode-earnings')||'[]');render()}
window.addEventListener('storage',reloadSharedState);window.addEventListener('focus',reloadSharedState);document.addEventListener('visibilitychange',()=>{if(!document.hidden)reloadSharedState()});
render();updateConnectionUI();
